name: Keep Render Awake

on:
  schedule:
    - cron: "*/10 * * * *"  # every 10 minutes

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Production(Render)
        run: |
          curl -s https://call-logs-api.onrender.com/health
          
      - name: Ping UAT(render)
        run: |
          curl -s https://call-logs-api-uat.onrender.com/health

